### ISSUE TITLE
Channels with Unique characters causes crash when downloading

### ISSUE THREAD

**Issue by bramnet** [Dannyman3819/Automatic-Youtube-Downloader#33]
When channels with unique/special characters that tend to break file directory standards, like the ? in DidYouKnowGamming? on Youtube, main.py crashes, leaving this as the final line in the log. 

03/08/2019 08:15:01 PM destination directory was not found for Download\DidYouKnowGaming?

**Comment by zyphermonkey** [comment]
Another channel is 'Make:' which is crashing on the ':'

**Comment by PizzaWaffles** [comment]
Newest version should fix these issues. See [this](https://github.com/Dannyman3819/Automatic-Youtube-Downloader#to-version-10) for updating to version 1.0

**Comment by bramnet** [comment]
The new version fixes the crashing. I've had slight difficulties with channels with the unusual characters' videos not saving correctly, but I'll open a separate issue for that due to the crashing being solved.

**Comment by bramnet** [comment]
I apologize for re-opening this up, but the issue is still occuring. I didn't realize this initially because apparently the last time I tried re-adding the channel using setup.py, I put in the ID as what was listed in the url (and it's an old channel so it's "DYKGaming") and didn't notice the error until I realized those haven't been downloaded. Now that it's been re-added, it's now crashing at a similar spot.
Log output:
Creating uploader destination directory for [output folder path]\DidYouKnowGaming?

**Comment by PizzaWaffles** [comment]
I'm having trouble reproducing your error, if you run the `python ./main.py` in the terminal what is the output? And what is your OS?

**Comment by bramnet** [comment]
The terminal output is:
`
Current Working Directory:E:\GitHub\Automatic-Youtube-Downloader

Checking Dependencies....
Python Path: C:\Users\Bram\AppData\Local\pypoetry\Cache\virtualenvs\Automatic-Youtube-Downloader-py3.6\Scripts\python.exe
Using Windows System Settings
Retrieving Poetry metadata

Latest version already installed.
Updating dependencies
Resolving dependencies...

Nothing to install or update

Complete.

--Using data/config
Downloading Icons....
Complete.
[youtube] mVMZB1BFFRI: Downloading webpage
[youtube] mVMZB1BFFRI: Downloading video info webpage
[youtube] mVMZB1BFFRI: Downloading webpage
[youtube] mVMZB1BFFRI: Downloading video info webpage
Video Quality: 248 - 1920x1080 (1080p)+251 - audio only (DASH audio)
[youtube] mVMZB1BFFRI: Downloading webpage
[youtube] mVMZB1BFFRI: Downloading video info webpage
Japan's Exclusive FromSoftware Games - Region Locked Feat. Dazz
[youtube] mVMZB1BFFRI: Downloading thumbnail ...
[youtube] mVMZB1BFFRI: Writing thumbnail to: Download\DidYouKnowGaming\Japans Exclusive FromSoftware Games   Region Locked Feat. Dazz - [mVMZB1BFFRI].jpg
[download] Destination: Download\DidYouKnowGaming\Japans Exclusive FromSoftware Games   Region Locked Feat. Dazz - [mVMZB1BFFRI].f248.webm
[download] 100% of 198.21MiB in 01:03
[download] Destination: Download\DidYouKnowGaming\Japans Exclusive FromSoftware Games   Region Locked Feat. Dazz - [mVMZB1BFFRI].f251.webm
[download] 100% of 13.77MiB in 00:04
[ffmpeg] Merging formats into "Download\DidYouKnowGaming\Japans Exclusive FromSoftware Games   Region Locked Feat. Dazz - [mVMZB1BFFRI].webm"
Deleting original file Download\DidYouKnowGaming\Japans Exclusive FromSoftware Games   Region Locked Feat. Dazz - [mVMZB1BFFRI].f248.webm (pass -k to keep)
Deleting original file Download\DidYouKnowGaming\Japans Exclusive FromSoftware Games   Region Locked Feat. Dazz - [mVMZB1BFFRI].f251.webm (pass -k to keep)
Traceback (most recent call last):
  File "AYD.py", line 753, in <module>
    start()
  File "AYD.py", line 749, in start
    main(sch)
  File "AYD.py", line 626, in main
    os.makedirs(subscription_destination_dir)
  File "E:\Programs\Python36-32\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'E:\\Youtube Testing\\DidYouKnowGaming?'
`
I'm running Windows 10

**Comment by PizzaWaffles** [comment]
Found the issue, I was getting a new uploader value from youtube which included the question mark. I uploaded the fix, you only need to replace the AYD.py file if you don't want to re-download the entire repo.

**Comment by bramnet** [comment]
That appears to have solved the issue. Thanks.
